// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetSite(ctx context.Context, id int64) (Site, error)
	ListSites(ctx context.Context) ([]Site, error)
}

var _ Querier = (*Queries)(nil)
